In [1]:
import torch
a = torch.zeros(10)
b = torch.zeros(10)
a[0] += 1
b[1] += 1
age = torch.stack([a,b])
age_reprensentation = torch.rand((2,10,18,512))

/home/zelin/anaconda3/envs/GFPGAN/lib/python3.7/site-packages/tqdm/auto.py:22: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


In [41]:
c = torch.zeros(2,10)
for i in range(2):
    c[i][[0,1][i]] = 1
c

tensor([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [15]:
import torch
a = torch.rand(10,10,3)
b = a.flatten()
c = b.view(10,10,3)
((a-c)==0).sum()
length = b.shape[0]
d = torch.zeros(513*513*3)
d[:length] = b
d[-1] = length
e = d[:int(d[-1].item())]
original_length = int((d[-1]/3).sqrt().item())
f = e.view(original_length,original_length,3)
((a-f)==0).sum()

tensor(300)

In [56]:
import numpy as np

type(np.zeros(100)) is np.ndarray

True

In [51]:
for i in zip(*[torch.zeros((1,41,41)),torch.zeros((1,1))]):
    print(i[1].shape)

torch.Size([1])


In [44]:
def cal(a,b):
    return a+b
cal(*[5,1])

6

In [35]:
(age.unsqueeze(2).unsqueeze(2) * age_reprensentation).sum(dim=1)[0]

tensor([[0.0179, 0.9335, 0.6417,  ..., 0.6251, 0.0137, 0.7818],
        [0.1004, 0.9747, 0.3670,  ..., 0.2510, 0.9682, 0.6177],
        [0.2818, 0.7724, 0.2985,  ..., 0.6144, 0.7845, 0.8550],
        ...,
        [0.9342, 0.9256, 0.8677,  ..., 0.7678, 0.7276, 0.0316],
        [0.1072, 0.4825, 0.9278,  ..., 0.9166, 0.6448, 0.5595],
        [0.1404, 0.1458, 0.9652,  ..., 0.5565, 0.8684, 0.0304]])

In [36]:
(age.unsqueeze(2).unsqueeze(2) * age_reprensentation)[0][0]

tensor([[0.0179, 0.9335, 0.6417,  ..., 0.6251, 0.0137, 0.7818],
        [0.1004, 0.9747, 0.3670,  ..., 0.2510, 0.9682, 0.6177],
        [0.2818, 0.7724, 0.2985,  ..., 0.6144, 0.7845, 0.8550],
        ...,
        [0.9342, 0.9256, 0.8677,  ..., 0.7678, 0.7276, 0.0316],
        [0.1072, 0.4825, 0.9278,  ..., 0.9166, 0.6448, 0.5595],
        [0.1404, 0.1458, 0.9652,  ..., 0.5565, 0.8684, 0.0304]])